# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' # SDK Version to use.
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the sln
        run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to NuGet
        run: dotnet nuget push */bin/Release/*.nupkg -k ${{ secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish the package to GPR
        run: dotnet nuget push */bin/Release/*.nupkg -k ${{ secrets.GPR_KEY }} -s https://nuget.pkg.github.com/alex8obrien/index.json --skip-duplicate